### ISSUE TITLE
Asymetric support of maps with numeric keys

### ISSUE THREAD

**Issue by plokhotnyuk** [rallyhealth/weePickle#48]
weePickle 1.3.0 decodes `{"1":true}` to `Map[Int, Boolean]` and `mutable.Map[Int, Boolean]` values successfully but cannot serialize them back by throwing the following error:
```
expected string key got int32
com.rallyhealth.weepickle.v1.core.Abort: expected string key got int32
	at com.rallyhealth.weepickle.v1.core.SimpleVisitor.visitInt32(SimpleVisitor.scala:32)
	at com.rallyhealth.weepickle.v1.core.SimpleVisitor.visitInt32$(SimpleVisitor.scala:32)
	at com.rallyhealth.weejson.v1.jackson.JsonGeneratorVisitor$$anon$1.visitInt32(JsonGeneratorVisitor.scala:25)
	at com.rallyhealth.weepickle.v1.implicits.DefaultFroms$$anon$4.transform0(DefaultFroms.scala:28)
	at com.rallyhealth.weepickle.v1.implicits.DefaultFroms$$anon$4.transform0(DefaultFroms.scala:27)
	at com.rallyhealth.weepickle.v1.core.Types$From.transform(Types.scala:118)
	at com.rallyhealth.weepickle.v1.core.Types$From.transform$(Types.scala:116)
	at com.rallyhealth.weepickle.v1.implicits.DefaultFroms$$anon$4.transform(DefaultFroms.scala:27)
	at com.rallyhealth.weepickle.v1.implicits.DefaultFroms$$anon$13.$anonfun$transform0$1(DefaultFroms.scala:94)
	at com.rallyhealth.weepickle.v1.implicits.DefaultFroms$$anon$13.$anonfun$transform0$1$adapted(DefaultFroms.scala:91)
	at scala.collection.mutable.HashMap$Node.foreach(HashMap.scala:608)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:481)
	at com.rallyhealth.weepickle.v1.implicits.DefaultFroms$$anon$13.transform0(DefaultFroms.scala:91)
	at com.rallyhealth.weepickle.v1.implicits.DefaultFroms$$anon$13.transform0(DefaultFroms.scala:88)
	at com.rallyhealth.weepickle.v1.core.Types$From.transform(Types.scala:118)
	at com.rallyhealth.weepickle.v1.core.Types$From.transform$(Types.scala:116)
	at com.rallyhealth.weepickle.v1.implicits.DefaultFroms$$anon$13.transform(DefaultFroms.scala:88)
	at com.rallyhealth.weepickle.v1.Api$$anon$1.transform(Api.scala:31)
	at com.github.plokhotnyuk.jsoniter_scala.benchmark.MutableMapOfIntsToBooleansWriting.weePickle(MutableMapOfIntsToBooleansWriting.scala:41)
	at com.github.plokhotnyuk.jsoniter_scala.benchmark.MutableMapOfIntsToBooleansWritingSpec.$anonfun$new$2(MutableMapOfIntsToBooleansWritingSpec.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.wordspec.AnyWordSpec.withFixture(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
	at org.scalatest.wordspec.AnyWordSpec.runTest(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
	at org.scalatest.wordspec.AnyWordSpec.runTests(AnyWordSpec.scala:1879)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.wordspec.AnyWordSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
	at org.scalatest.wordspec.AnyWordSpec.run(AnyWordSpec.scala:1879)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:40)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```
[Here](https://github.com/plokhotnyuk/jsoniter-scala/commit/0ce2b986afbedeb60b8e723f6c984dc059e749d4) are tests and code to reproduce.

**Comment by htmldoug** [comment]
Thanks for reporting!

It's an interaction between https://github.com/rallyhealth/weePickle/pull/28/files#diff-d0205c5025b12a9d22fce5ffd2b08183R194 to support `Map[Enum, T]` and https://github.com/rallyhealth/weePickle/pull/46/files#diff-d0205c5025b12a9d22fce5ffd2b08183R52 which adds tolerant coersions from `String` to `Int` (cc: @russellremple). From your tests, it looks like many [other implementations](https://github.com/plokhotnyuk/jsoniter-scala/commit/0ce2b986afbedeb60b8e723f6c984dc059e749d4#diff-7e99647b93420ed95b39f9d4012da6fbR25-R30) are strict, and will not coerce from `String` to `Int`.

If we wanted to support the symmetric `Map[Int, T]` to `{"1": ...}` without throwing, it's tricky. "Keys must be strings" applies to JSON, but not MsgPack, so any coercion would probably have to happen at that layer, i.e. near [here](https://github.com/rallyhealth/weePickle/blob/9efc5961a9e2f76af4445535400c3b625c70b008/weejson/jackson/src/com/rallyhealth/weejson/v1/jackson/JsonGeneratorVisitor.scala#L25-L32). IIRC, @BurgersMcSlopshot mentioned that the C# libs he's familiar with do something similar.

It looks like newer versions of jackson-core have [writeFieldId(long)](https://github.com/FasterXML/jackson-core/blob/65e36eef9b9e5b978618d4f70102bf10d942426f/src/main/java/com/fasterxml/jackson/core/JsonGenerator.java#L433-L441). This would only provide symmetry for non-floats, but we should probably hook it up regardless in case a `JsonGenerator` for a binary format overrides it.

If the jackson default behavior is to convert non-floats to `String` keys, it seems like good precedent for us to do the same for floats and booleans as well since our `To[Double]` and `To[Boolean]` already handle reading string inputs in the other direction.

Thoughts welcome.

**Comment by htmldoug** [comment]
https://github.com/rallyhealth/weePickle/releases/tag/v1.3.1
